# Generated by Django 5.2.17 on 2026-08-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctorprofile_labstaffprofile_patientprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('LAB', 'Lab Staff'), ('PHARMACY', 'Pharmacy Staff')], default='PATIENT', max_length=20),
        ),
    ]
